### ISSUE TITLE
Could not run aspect term extractor

### ISSUE THREAD

**Issue by arsalanamjid** [AkshitaJha/IRE#1]
` python aspect_term1.py
Traceback (most recent call last):
  File "aspect_term1.py", line 133, in <module>
    main()
  File "aspect_term1.py", line 78, in main
    aspect_term = getAspectTermsDict(sys.argv[1])
IndexError: list index out of range
`

**Comment by nxjiten** [comment]
pass the parameter python aspect_term1.py  'text'. text is taken as sys.argv[1].
